version: '3'
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
  api:
    build: ./api/
    environment:
      - MONGO_URL=mongodb://mongodb:27017/fakedb
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - mongodb
  web:
    build: ./web/
    environment:
      - API_URL=http://localhost:3000
    ports:
      - "1234:1234"
    volumes:
      - ./web:/usr/src/app
    depends_on:
      - api
